### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by LaAlexita** [overextended/ox_mdt#5] opened 2023-09-04 14:31 UTC
/* SQL Error (1005): Can't create table `s1004_servidor`.`ox_mdt_reports_criminals` (errno: 150 "Foreign key constraint is incorrectly formed") */

**Comment by LukeWasTakenn** [comment] 2023-09-04 14:32
Duplicate of #1

**Closed by LukeWasTakenn** 2023-09-04 14:32 UTC
